//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confabulation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Confabulation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ConnectText {
            get {
                return ResourceManager.GetString("ConnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string DisconnectText {
            get {
                return ResourceManager.GetString("DisconnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now known as {0}.
        /// </summary>
        internal static string SelfChangedNickname {
            get {
                return ResourceManager.GetString("SelfChangedNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You changed the topic to &apos;{0}&apos;.
        /// </summary>
        internal static string SelfChangedTopic {
            get {
                return ResourceManager.GetString("SelfChangedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cleared the topic.
        /// </summary>
        internal static string SelfClearedTopic {
            get {
                return ResourceManager.GetString("SelfClearedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You went offline.
        /// </summary>
        internal static string SelfDisconnected {
            get {
                return ResourceManager.GetString("SelfDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered the channel.
        /// </summary>
        internal static string SelfJoinedChannel {
            get {
                return ResourceManager.GetString("SelfJoinedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were kicked by {0}.
        /// </summary>
        internal static string SelfKickedByUser {
            get {
                return ResourceManager.GetString("SelfKickedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You kicked {0}.
        /// </summary>
        internal static string SelfKickedUser {
            get {
                return ResourceManager.GetString("SelfKickedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have left the channel.
        /// </summary>
        internal static string SelfPartedChannel {
            get {
                return ResourceManager.GetString("SelfPartedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now known as {1}.
        /// </summary>
        internal static string UserChangedNickname {
            get {
                return ResourceManager.GetString("UserChangedNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed the topic to &apos;{1}&apos;.
        /// </summary>
        internal static string UserChangedTopic {
            get {
                return ResourceManager.GetString("UserChangedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cleared the topic.
        /// </summary>
        internal static string UserClearedTopic {
            get {
                return ResourceManager.GetString("UserClearedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entered the channel.
        /// </summary>
        internal static string UserJoinedChannel {
            get {
                return ResourceManager.GetString("UserJoinedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was kicked by {1}.
        /// </summary>
        internal static string UserKicked {
            get {
                return ResourceManager.GetString("UserKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left the channel.
        /// </summary>
        internal static string UserPartedChannel {
            get {
                return ResourceManager.GetString("UserPartedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} went offline.
        /// </summary>
        internal static string UserQuit {
            get {
                return ResourceManager.GetString("UserQuit", resourceCulture);
            }
        }
    }
}
